### ISSUE TITLE
Script Optimization

### ISSUE THREAD

**Issue by bzhazreal** [7rin0/vagrantApps#2]
Hello !

Maybe you can optimize your script install.sh by running :
`sudo apt-get install -y \
php5 \
libapache2-mod-php5 \
php5-dev \
php5-mcrypt \
php5-curl \
php5-gd \
php5-cli \
php5-mysql \
pdo-mysql
`
instead of :
sudo apt-get install php5 -y
sudo apt-get install php5 libapache2-mod-php5 -y
sudo apt-get install php5-dev -y
sudo apt-get install php5-mcrypt -y
sudo apt-get install php5-curl -y
sudo apt-get install php5-gd -y
sudo apt-get install php5-cli -y
sudo apt-get install php5-mysql -y
sudo apt-get install pdo-mysql -y

By this way apt calculate dependencies only once.

With the same idea, you restart Apache twice at line 31 and 49, you can restart Apache only at the end.

**Comment by 7rin0** [comment]
Hi bzhazreal,

that's a good point can you make a PR please?

Thanks :-)
